config/routes.rb
Rails.application.routes.draw do
  root 'admin#index'

  resources :orders, only: [:index, :show], param: :number

  resources :reports, only: :index do
  end

  post '/reports/coupon_select' => 'reports#coupon_select', as: "coupon_select"
  post '/reports/product_sales' => 'reports#product_sales', as: "product_sales"
end

app/models/address.rb
class Address < ApplicationRecord
  validates_presence_of   :address1, :city, :state, :user_id
  validates_uniqueness_of :user_id

  validates :zipcode,
            format: {
              with: /\A\d{5}\z/,
              message: "not valid. Please enter your 5 digit zipcode"
            }, presence: true

  belongs_to :user

  has_many   :orders
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/coupon.rb
class Coupon < ApplicationRecord
  validates_presence_of :name

  validates   :amount,
              presence: true,
              numericality: {
                greater_than_or_equal_to: 0
              },
              format: {
                with: /\A-?\d+\.?\d{0,2}\z/,
                message: 'only accepts 2 decimal places.'
              }

  has_many :order_items,
           as: :source
end

app/models/order.rb
class Order < ApplicationRecord
  BUILDING = "building"
  ARRIVED = "arrived"
  CANCELED = "canceled"
  STATES = [BUILDING, ARRIVED, CANCELED].freeze

  validates_presence_of :user_id, :state

  validates   :total,
              presence: true,
              format: {
                with: /\A-?\d+\.?\d{0,2}\z/,
                message: 'only accepts 2 decimal places.'
              }

  belongs_to :user
  belongs_to :address

  has_many :order_items
  has_many :payments

  paginates_per 10

  def to_param
    number
  end
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  SOLD = "sold"
  RETURNED = "returned"
  STATES = [SOLD, RETURNED].freeze
  validates_presence_of :order_id, :source_id, :source_type, :price

  validates :state,
            absence: true,
            if: -> { source_type != Product.name }

  validates :state,
            allow_nil: false,
            inclusion: STATES,
            if: -> { source_type == Product.name && order.building_at.present? }

  validates :quantity,
            presence: true,
            numericality: {
              greater_than: 0
            }

  belongs_to :order
  belongs_to :source,
             polymorphic: true

  scope :sold, -> { where(state: 'sold')}
  scope :ordered_between, ->(start_date, end_date) { where(created_at: start_date..end_date) }
end

app/models/payment.rb
class Payment < ApplicationRecord
  COMPLETED = "completed"
  REFUNDED = "refunded"
  STATES = [COMPLETED, REFUNDED].freeze

  CREDIT_CARD = "CreditCard"
  STORE_CREDIT = "StoreCredit"
  PAYMENT_TYPES = [CREDIT_CARD, STORE_CREDIT].freeze

  validates_presence_of :order_id, :state, :payment_type

  validates   :amount,
              presence: true,
              format: {
                with: /\A-?\d+\.?\d{0,2}\z/,
                message: 'only accepts 2 decimal places.'
              }

  belongs_to :order
end

app/models/product.rb
class Product < ApplicationRecord
  validates_presence_of :name

  validates   :sku,
              presence: true,
              uniqueness: true

  validates   :msrp,
              presence: true,
              numericality: {
                greater_than_or_equal_to: 0
              },
              format: {
                with: /\A-?\d+\.?\d{0,2}\z/,
                message: 'only accepts 2 decimal places.'
              }

  validates   :cost,
              presence: true,
              numericality: {
                greater_than_or_equal_to: 0
              },
              format: {
                with: /\A-?\d+\.?\d{0,2}\z/,
                message: 'only accepts 2 decimal places.'
              }

  has_many :order_items,
           as: :source

  scope :with_sales_between_dates, ->(start_date, end_date) {
    joins(:order_items).merge(OrderItem.sold.ordered_between(start_date, end_date)) }
end

app/models/tax.rb
class Tax < ApplicationRecord
  validates :name,
            presence: true

  validates :rate,
            presence: true,
            numericality: {
              greater_than_or_equal_to: 0,
              less_than_or_equal_to: 1
            },
            format: {
              with: /\A-?\d+\.?\d{0,3}\z/,
              message: 'only accepts 3 decimal places.'
            }

  has_many :order_items,
           as: :source
end

app/models/user.rb
class User < ApplicationRecord

  validates :name,
            presence: true

  validates :email,
            presence: true,
            uniqueness: true

  has_many :orders
  has_many :addresses
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  def index
    @users = User.all
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :find_order!, only: :show

  def index
    @search = Order.ransack(params[:q])
    # make name the default sort column
    @search.sorts = 'number' if @search.sorts.empty?
    @orders = @search.result
                  .includes(:user)
                  .page params[:page]
    @search.build_condition
  end

  def show
  end

  private
  def find_order!
    @order = Order.find_by!(number: params[:number])
  end
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  skip_before_action :verify_authenticity_token

  def index
    @coupons = Coupon.all
    # Product.with_sales_between_dates(DateTime.strptime(s.to_s, '%s'), e)
    start_date = DateTime.strptime(0.to_s, '%s')
    end_date = Time.now
    @products = Product.includes(:order_items).
        with_sales_between_dates(start_date, end_date).
        order(:name).uniq
  end

  def coupon_select
    render partial: "coupon_results", locals: {coupon: Coupon.find(params[:coupon_id])}
  end

  def product_sales
    start_date = DateTime.strptime(params[:start_date], '%s')
    end_date = DateTime.strptime(params[:end_date], '%s')
    products = Product.includes(:order_items).
        with_sales_between_dates(start_date, end_date).
        order(:name).uniq
    render partial: "product_sales", locals: {products: products}
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/index.haml
.jumbotron
  %h1
    Code Challenge for Wantable
  %h2
    Candidate: Aaron Jacobs
  %p
    = link_to "314.749.2604", "tel:13147492604"
  %p
    = link_to "Schedule a Meeting", "https://calendly.com/aaronejacobs/60min", {class: "btn btn-primary btn-lg", role: "button", target: "_blank"}
  %p
    = link_to "Resume", "https://docs.google.com/document/d/1I1e0q6zSkVxqTUhu2s8h8Bb_V67cai55Vyi0eH_lBAw/edit?usp=sharing", {class: "btn btn-primary btn-lg", role: "button", target: "_blank"}
    = mail_to "aaron8153@gmail.com", "Email", {class: "btn btn-primary btn-lg", role: "button", target: "_blank"}

app/views/layouts/application.haml
!!!
%html
  %head
    %title CodeChallenge

    = csrf_meta_tags
    = csp_meta_tag
    = tag "meta", "http-equiv" => "Accept-CH", content: "DPR, Viewport-Width, Width"
    = tag 'meta', {"http-equiv" => "Accept-CH", content: "width=device-width, initial-scale=1.0, user-scalable=no", name: "viewport", id: "vp"}, true
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    = javascript_include_tag "https://cdn.jsdelivr.net/momentjs/latest/moment.min.js", :type => "text/javascript"
    = javascript_include_tag "https://cdn.jsdelivr.net/npm/daterangepicker/daterangepicker.min.js", :type => "text/javascript"
    = stylesheet_link_tag "https://cdn.jsdelivr.net/npm/daterangepicker/daterangepicker.css", :type => "text/css"

  %body
    %nav.navbar.navbar-default.navbar-fixed-top
      .container-fluid
        .navbar-header
          =link_to root_path, class: "navbar-brand" do
            =image_tag "logo"

        .collapse.navbar-collapse
          %ul.nav.navbar-nav
            %li{class: current_page?(controller: "orders") ? 'active' : ''}
              =link_to orders_path do
                Orders

            %li{class: current_page?(controller: "reports") ? 'active' : ''}
              =link_to reports_path do
                Reports

    .container-fluid{role: "main"}
      = yield

app/views/orders/_address.haml
%h2
  Address
%table.table.table-striped.address
  %tr
    %th.address1= "Address"
    %th.address2= "Address Cont."
    %th.city= "City"
    %th.state= "State"
    %th.user_id= "User ID"
    %th.zipcode= "Zip"
  %tr
    %td.address1= @order.address.address1
    %td.address2= @order.address.address2
    %td.city= @order.address.city
    %td.state= @order.address.state
    %td.user_id= @order.address.user_id
    %td.zipcode= @order.address.zipcode

app/views/orders/_order_items.haml
%h2
  Order Items
%table.table.table-striped.order_items
  %tr
    %th.order_id= "Order ID"
    %th.price= "Price"
    %th.quantity= "Quantity"
    %th.source_id= "Source Id"
    %th.source_type= "Source Type"
  - @order.order_items.each do |order_item|
    %tr
      %td.order_id= order_item.order_id
      %td.price= order_item.price
      %td.quantity= order_item.quantity
      %td.source_id= order_item.source_id
      %td.source_type= order_item.source_type

app/views/orders/_payments.haml
%h2
  Payments
%table.table.table-striped.payments
  %tr
    %th.amount= "Amount"
    %th.completed_at= "Completed At"
    %th.payment_type= "Payment Type"
    %th.order_id= "Order Id"
    %th.refunded_at= "Refunded At"
    %th.state= "State"
  - @order.payments.each do |payment|
    %tr
      %td.amount= payment.amount
      %td.completed_at= payment.completed_at
      %td.payment_type= payment.payment_type
      %td.order_id= payment.order_id
      %td.refunded_at= payment.refunded_at
      %td.state{class: payment.state}= payment.state.capitalize

app/views/orders/_user.haml
%h2
  User
%table.table.table-striped.user
  %tr
    %th.user= "Name"
    %th.email= "Email"
  %tr
    %td.user= @order.user.name
    %td.email= @order.user.email

app/views/orders/index.haml
%h3
  Orders

.row.mb-20
  .col-xs-6
    Search Form:
    %br/
    = search_form_for @search do |f|
      = f.condition_fields do |c|
        .row.mb-10
          = c.attribute_fields do |a|
            .col-xs-3.form-group
              = a.attribute_select nil, class: 'form-control'
          .col-xs-3.form-group
            = c.predicate_select({only: [:cont, :lteq, :gteq]}, {class: 'form-control'})
          = c.value_fields do |v|
            .col-xs-6
              = v.text_field :value, class: 'form-control'
      = f.submit class: 'btn btn-primary'
      = link_to "Reset Search", orders_path

.row
  .col-xs-12
    %table.table.table-striped.orders
      %tr
        %th.number= sort_link @search, :number, "Number"
        %th.state= sort_link @search, :state, "State"
        %th.user_name= sort_link @search, :user_name, "User"
        %th.user_email= sort_link @search, :user_email, "Email"
      - @orders.each do |order|
        %tr
          %td.number
            = link_to order.number.to_s, order_path(order.number)
          %td.state{:class => order.state}= order.state.capitalize
          %td.user_name= order.user.name
          %td.user_email= order.user.email
    = paginate @orders

app/views/orders/show.haml
%h3
  = "Order " + @order.number
  %span{class: @order.state}= @order.state.capitalize

.row.mb-20
  .col-xs-12
    = render :partial => "user"
    = render :partial => "address"
    = render :partial => "order_items"
    = render :partial => "payments"

app/views/reports/_coupon_results.haml
%h2
  Order Items
%table.table.table-striped.order_items
  %tr
    %th.order_id= "User Email"
    %th.number_of= "Number of"
    %th.before_coupons= "Total Before Coupons"
    %th.coupons_amt= "Coupon Amount"
    %th.revenue= "Revenue"
  - coupon.order_items.each do |order_item|
    %tr
      %td.order_id= order_item.order.user.email
      %td.number_of= order_item.quantity
      %td.before_coupons= number_to_currency order_item.order.total
      %td.coupons_amt= number_to_currency (order_item.price * order_item.quantity)
      %td.revenue= number_to_currency(order_item.order.total + (order_item.price * order_item.quantity))

app/views/reports/_product_sales.haml
%h2
  Product Sales
%table.table.table-striped.order_items
  %tr
    %th.name= "Product Name"
    %th.sold_count= "Number Sold"
    %th.revenue= "Revenue"
  - products.each do |product|
    - sold_count = 0
    - revenue = 0
    - product.order_items.each do |order_item|
      - sold_count += order_item.quantity
      - revenue += order_item.price * order_item.quantity
    %tr
      %td.name= product.name
      %td.sold_count= sold_count
      %td.revenue= number_to_currency revenue

app/views/reports/index.haml
%h3
  Coupon Users

.row.mb-20
  .col-xs-6
    %form
      = select_tag :coupon_id, options_from_collection_for_select(@coupons, "id", "name"), class: "form-control", "ic-post-to" => coupon_select_path, "ic-target" => "#results"
.row
  .col-xs-12#results
    = render partial: "coupon_results", locals: {coupon: @coupons.first}

%h3
  Sales By Product

.row.mb-20
  .col-xs-4
    #daterange{style: "background: #fff; cursor: pointer; padding: 5px 10px; border: 1px solid #ccc; width: 100%"}
      %i.fa.fa-calendar
        &nbsp;
      %span
      %i.fa.fa-caret-down
    -# = select_tag :product_id, options_from_collection_for_select(@products, "id", "name"), class: "form-control", "ic-post-to" => coupon_select_path, "ic-target" => "#product-results"
.row
  .col-xs-12#product-results
    = render partial: "product_sales", locals: {products: @products}